import logging
import os
import smtplib

from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

from config import EMAIL_ENABLED, REPORT_RECIPIENT_EMAIL

logger = logging.getLogger(__name__)


def send_screening_email(
    name,
    email,
    age,
    gender,
    prediction,
    probability,
    timestamp,
    **_
):
    """
    Send the autism screening result to:
    1. Patient's email
    2. Doctor's email
    """

    if not EMAIL_ENABLED:
        logger.info("Email sending is disabled.")
        return "Email sending is disabled."

    # Get Gmail configuration from .env
    sender_email = os.getenv("GMAIL_EMAIL")
    app_password = os.getenv("GMAIL_APP_PASSWORD")
    report_recipient = REPORT_RECIPIENT_EMAIL or os.getenv("DOCTOR_EMAIL")

    # Validate configuration
    if not sender_email:
        return "Email sending failed: GMAIL_EMAIL is not configured."

    if not app_password:
        return "Email sending failed: GMAIL_APP_PASSWORD is not configured."

    if not email:
        return "Email sending failed: Patient email is missing."

    if not report_recipient:
        return "Email sending failed: REPORT_RECIPIENT_EMAIL is not configured."

    # Calculate result
    risk_level = "Higher Risk" if prediction == "YES" else "Lower Risk"
    risk_percentage = probability * 100

    # Email subject
    subject = "Autism Screening Result"

    # HTML email body
    html_body = f"""
    <html>
    <body style="
        font-family: Arial, sans-serif;
        line-height: 1.6;
        color: #333;
    ">

        <h2>Autism Screening Report</h2>

        <p>Hello <strong>{name}</strong>,</p>

        <p>
            Your autism screening has been completed.
            Please find your screening result below.
        </p>

        <hr>

        <h3>Screening Details</h3>

        <table style="
            border-collapse: collapse;
            width: 100%;
            max-width: 600px;
        ">

            <tr>
                <td style="padding: 8px; border: 1px solid #ddd;">
                    <strong>Patient Name</strong>
                </td>
                <td style="padding: 8px; border: 1px solid #ddd;">
                    {name}
                </td>
            </tr>

            <tr>
                <td style="padding: 8px; border: 1px solid #ddd;">
                    <strong>Age</strong>
                </td>
                <td style="padding: 8px; border: 1px solid #ddd;">
                    {age}
                </td>
            </tr>

            <tr>
                <td style="padding: 8px; border: 1px solid #ddd;">
                    <strong>Gender</strong>
                </td>
                <td style="padding: 8px; border: 1px solid #ddd;">
                    {gender}
                </td>
            </tr>

            <tr>
                <td style="padding: 8px; border: 1px solid #ddd;">
                    <strong>AI Screening Result</strong>
                </td>
                <td style="padding: 8px; border: 1px solid #ddd;">
                    {risk_level}
                </td>
            </tr>

            <tr>
                <td style="padding: 8px; border: 1px solid #ddd;">
                    <strong>Risk Probability</strong>
                </td>
                <td style="padding: 8px; border: 1px solid #ddd;">
                    {risk_percentage:.2f}%
                </td>
            </tr>

            <tr>
                <td style="padding: 8px; border: 1px solid #ddd;">
                    <strong>Date and Time</strong>
                </td>
                <td style="padding: 8px; border: 1px solid #ddd;">
                    {timestamp}
                </td>
            </tr>

        </table>

        <hr>

        <h3>Recommendation</h3>

        <p>
            {
                "The screening indicates a higher likelihood of autism-related traits. "
                "Please consult a qualified healthcare professional for further evaluation."
                if prediction == "YES"
                else
                "The screening indicates a lower likelihood of autism-related traits. "
                "If you have concerns, please consult a qualified healthcare professional."
            }
        </p>

        <hr>

        <p>
            <strong>Important:</strong>
        </p>

        <p>
            This result is generated by an Artificial Intelligence and Machine Learning
            screening system. This result is <strong>not a medical diagnosis</strong>.
            Please consult a qualified healthcare professional for medical evaluation.
        </p>

        <p>
            Thank you for using the Autism Screening System.
        </p>

    </body>
    </html>
    """

    try:
        # Create email
        message = MIMEMultipart("alternative")

        message["From"] = sender_email

        # Patient sees only their own email
        message["To"] = email

        # The configured report recipient receives a private copy.
        message["Bcc"] = report_recipient

        message["Subject"] = subject

        # Attach HTML body
        message.attach(MIMEText(html_body, "html"))

        # Connect to Gmail SMTP
        with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:

            # Login using Gmail + App Password
            server.login(
                sender_email,
                app_password
            )

            # The envelope must include every recipient, including Bcc.
            server.sendmail(
                sender_email,
                [email, report_recipient],
                message.as_string()
            )

        print("Screening email sent successfully!")
        print("Patient:", email)
        print("Report recipient:", report_recipient)

        return "Screening email sent successfully."

    except Exception as error:

        logger.exception(
            "Failed to send screening email: %s",
            error
        )

        return f"Email sending failed: {error}"